import json, random, requests, datetime
from thefuzz import process
from typing import Dict, Any
from PIL import Image, ImageDraw, ImageFont
from utils.utils import get_IO_path, get_copyright_str, get_output_path
from utils.fonts import get_font
from nonebot.adapters.onebot.v11 import MessageSegment

song_info_path = get_IO_path("phigros_song_list", "json")
tip_path = get_IO_path("phigros_tips", "json")
version_path = get_IO_path("phigros_version_info", "json")

def search_similar_song(songname: str) -> str:
    with open(song_info_path, "r", encoding="utf-8") as f: music_info = json.load(f)
    return process.extractOne(songname, [music["song"] for _, music in music_info.items()])[0]

def get_song_info(songname: str) -> Dict[str, Any]:
    with open(song_info_path, "r", encoding="utf-8") as f: song_info = json.load(f)
    for _, song in song_info.items():
        if song["song"] == songname:
            return song
        
def song_preprocess(_song: Dict[str, Any]) -> Dict[str, Any]:
    song = {}
    illustration_path = get_output_path("phigros_illustration", temp = True)
    with open(illustration_path, "wb") as f: f.write(requests.get(_song["illustration_big"]).content)
    song["cover_url"] = illustration_path
    song["title"] = _song["song"]
    song["artist"] = _song["composer"]
    song["bpm"] = _song["bpm"]
    for difficulty in ["EZ", "HD", "IN", "AT"]:
        if difficulty in _song["chart"]: song[difficulty] = _song["chart"][difficulty]["difficulty"]
    return song
    
def get_embedded_font(size: int) -> ImageFont:
    return ImageFont.FreeTypeFontFamily(get_font("Saira", size = size), get_font("sourcehan-sans", size = size))

async def create_song_image(song_data: Dict[str, Any]) -> MessageSegment:
    cover_img = Image.open(song_data["cover_url"])
    
    width, height = 1600, 1000  
    background_color = (45, 45, 45)
    difficulty_colors = {"EZ":(50, 205, 50),"HD":(30, 144, 255),"IN":(255, 69, 0),"AT":(169, 169, 169)}
    
    img = Image.new("RGB", (width, height), background_color)
    draw = ImageDraw.Draw(img)
    difficulty_font = get_embedded_font(32) 
    
    cover_width = width - 600 
    cover_height = int(cover_width * (1080 / 2048))
    cover_resized = cover_img.resize((cover_width, cover_height))
    cover_x = (width - cover_width) // 2
    cover_y = 50
    img.paste(cover_resized, (cover_x, cover_y))

    title_y = cover_y + cover_resized.height + 80
    draw.text((width // 2, title_y), song_data["title"], font=get_embedded_font(48), fill=(255, 255, 255), anchor="mm")

    artist_y = title_y + 60
    draw.text((width // 2, artist_y), song_data["artist"], font=get_embedded_font(36), fill=(255, 255, 255), anchor="mm")

    difficulty_texts = []
    for key in ["EZ", "HD", "IN", "AT"]:
        if key in song_data: difficulty_texts.append((f"{key} {song_data[key]}", difficulty_colors[key]))

    difficulty_y = artist_y + 90

    total_width = 0
    for idx, (text, _) in enumerate(difficulty_texts):
        text_width = difficulty_font.getbbox(text)[2]
        total_width += text_width
        if idx < len(difficulty_texts) - 1: total_width += difficulty_font.getbbox(" / ")[2]

    x = (width - total_width) // 2
    for idx, (text, color) in enumerate(difficulty_texts):
        draw.text((x, difficulty_y), text, font=difficulty_font , fill=color, anchor="lm")
        x += difficulty_font.getbbox(text)[2]
        if idx < len(difficulty_texts) - 1:
            draw.text((x, difficulty_y), " / ", font=difficulty_font , fill=(255, 255, 255), anchor="lm")
            x += difficulty_font.getbbox(" / ")[2] 
        with open(tip_path, "r", encoding="utf-8") as f: _tips = json.load(f)

    tips = []
    for _, tip in _tips.items(): tips.extend(tip)
    tip = random.choice(tips).strip()

    with open(version_path, "r", encoding="utf-8") as f: _version_info = json.load(f)
    version_info = f"Resource Version: Phigros {_version_info['version']} | {_version_info['date']['year']}/{_version_info['date']['month']}/{_version_info['date']['day']}"

    copyright_text = "\u00A9" + f" Generated by Bi_Gu-bot at {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
    draw.text((20, height - 80), f"Tip: {tip}", fill=(255, 255, 255), font=get_embedded_font(24))
    draw.text((20, height - 10), copyright_text, fill=(255, 255, 255), font=get_embedded_font(24), anchor="lb")
    draw.text((width - 20, height - 10), version_info, fill=(255, 255, 255), font=get_embedded_font(24), anchor="rb")

    output_path = get_output_path("phigros_search_song")
    img.save(output_path)
    return MessageSegment.image("file:///" + output_path) 

async def phigros_search_song(songname: str) -> MessageSegment:
    song_data = song_preprocess(get_song_info(search_similar_song(songname)))
    return await create_song_image(song_data)