from PIL import Image, ImageDraw, ImageFont
import datetime, os
from nonebot.adapters.onebot.v11 import MessageSegment
from sys import path
path.append(os.getcwd() + "/utils")
from utils.fonts import get_font

def draw_help(helper_message: str, current_page: int, total_pages: int) -> MessageSegment:
    image_path = os.getcwd() + '/src/assets/images/help_background.png'
    original_image = Image.open(image_path).convert("RGBA")

    opacity = 160
    alpha = original_image.split()[3]
    alpha = Image.eval(alpha, lambda x: int(x * opacity / 255))
    original_image.putalpha(alpha)

    white_layer = Image.new('RGBA', original_image.size, (255, 255, 255, 0))
    white_opacity = 160
    white_alpha = white_layer.split()[3]
    white_alpha = Image.eval(white_alpha, lambda x: white_opacity)
    white_layer.putalpha(white_alpha)

    combined_image = Image.alpha_composite(original_image, white_layer)

    draw = ImageDraw.Draw(combined_image)
    font = get_font("yahei-consolas", size = 18)
 
    width, height = original_image.size
    draw.text((40, 20), helper_message, fill=(0, 0, 0, 255), font=font)
    draw.text((40, height-50), "\u00A9" + f" Generated by Bi_Gu-bot at {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}  |  Page {current_page} of {total_pages}", fill=(0, 0, 0, 255), font=font)

    output_path = os.getcwd() + f"/src/data/help/output/help_{datetime.datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
    combined_image.save(output_path)
    return MessageSegment.image('file:///' + output_path)