import datetime, requests
from typing import List, Any

def get_raw_user_data(username: str) -> List[Any]:
    params = {"name": username}
    response = requests.get('https://cdn.r-mj.com/r/chart3.php', params=params)
    return response.json()["data"]


def get_mahjongclub_info(username: str) -> str:
    raw_data = get_raw_user_data(username)
    res = [f"id: {raw_data[0]}", f"昵称: {raw_data[1]}", f"qq: {raw_data[3]}", f"rating: {raw_data[6]/1000}",
           "最近顺位:" + "".join([str(x) for x in raw_data[11]]),
           "最近打点:" + ", ".join([str(x*100) for x in raw_data[12]])]
    res.append("\u00A9 "+"Generated by Bi_Gu-bot at " + datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
    return "\n".join(res)



